name: Release flow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test-ts:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ts

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - run: npm ci
      - run: npm run typecheck
      - run: npm run build

  release:
    needs: test-ts
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.release.outputs.version }}
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - name: Run release please
        uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: simple

  publish-ts:
    needs: release
    if: needs.release.outputs.release_created == 'true'
    uses: ./.github/workflows/publish-ts.yml
    with:
      version: ${{ needs.release.outputs.version }}
    permissions:
      contents: read
      id-token: write